ReadyGOTravel/readygotravel/readygotravel/Models/Result.cs
namespace readygotravel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Result
    {
        public int ResultID { get; set; }

        public int SearchID { get; set; }

        public decimal AvgHotelStar { get; set; }

        [Column(TypeName = "money")]
        public decimal AvgFlightAmount { get; set; }

        [Column(TypeName = "money")]
        public decimal AvgHotelAmount { get; set; }

        [Column(TypeName = "money")]
        public decimal AvgFoodCost { get; set; }

        public virtual Search Search { get; set; }
    }
}

ReadyGOTravel/readygotravel/readygotravel/Models/Search.cs
namespace readygotravel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Search
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Search()
        {
            Results = new HashSet<Result>();
        }

        public int SearchID { get; set; }

        public int UserID { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }

        public int NumTravelers { get; set; }

        [Column(TypeName = "money")]
        public decimal MaxAmount { get; set; }

        public int? HotelStarValue { get; set; }

        [StringLength(2)]
        public string FlightType { get; set; }

        public int StartAirport { get; set; }

        public int EndAirport { get; set; }

        public virtual Airport Airport { get; set; }

        public virtual Airport Airport1 { get; set; }

        public virtual Person Person { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
    }
}

ReadyGOTravel/readygotravel/readygotravel/Controllers/SearchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Xml;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using readygotravel.Models;
using readygotravel.Models.ViewModels;
using Microsoft.AspNet.Identity;

namespace readygotravel.Controllers
{

    public class SearchesController : Controller
    {
        
        private DBContext db = new DBContext();
        private ApplicationDbContext userDB = new ApplicationDbContext();

        // GET: Searches
        public ActionResult Index()
        {
            var searches = db.Searches.Include(s => s.Person);
            return View(searches.ToList());
        }
        
        public ActionResult Result(int? id, decimal? left)
        {
            Result result = db.Results.Find(id);

            ViewBag.Remaining = left;
            ViewBag.Total = result.AvgFlightAmount + result.AvgHotelAmount + result.AvgFoodCost;
            //Makes sure that the average flight amount is not set to 0 or -1 as this would indicate errors
            if (result.AvgFlightAmount != (decimal)0.00 && result.AvgFlightAmount != (decimal)-1.00)
            {
                //Compare dollar amount available and update the ViewBag results accordingly. 
                if (left >= 0)
                {
                    ViewBag.Result = 0;
                    ViewBag.Message = "You can travel there for: ";
                    ViewBag.Message2 = "And you have this much remaining: ";
                }
                else if (left >= -500)
                {
                    ViewBag.Result = 1;
                    ViewBag.Message = "You can almost go if you had amount this much more: ";
                }
                else
                {
                    ViewBag.Result = 2;
                    ViewBag.Message = "You are too broke and can't go on that budget, you would need this much more: ";
                }

                
                //Check if the decimal value is 0, if so skip this.
                decimal num = RoundToFourths(result.AvgHotelStar);
                //Get the whole number of the rounded number
                decimal integral = Math.Truncate(num);
                //Get the decimal value of the rounded number
                decimal @decimal = num - integral;

                //Set the whole number and decimal to the View.
                ViewBag.Stars = integral;
                ViewBag.Decimal = @decimal;
            }
            else if(result.AvgFlightAmount == -1)
            {
                ViewBag.Result = 3;
                ViewBag.Message = "Oops your ending location was the same as your starting location!";
                ViewBag.Message2 = "Please update your search options and try again.";
            }
            else
            {
                ViewBag.Result = 4;
                ViewBag.Message = "No flights were available that matched your search criteria.";
                ViewBag.Message2 = "Please update your search options and try again.";
            }

            ViewBag.NumDays = (result.Search.EndDate - result.Search.StartDate).Days;

            //Present information to user
            return View(result);
        }

        //This method is TESTABLE!!
        public decimal RoundToFourths(decimal num)
        {
            bool positive = true;
            //if num is negative, make it positive and reset the bool value.
            if (num < 0)
            {
                num = num * (-1);
                positive = false;
            }

            decimal integral = Math.Truncate(num);
            decimal @decimal = num - integral;
                     
            //If the decimal value is less than 0.12 set the decimal value to 0.
            if (@decimal <= (decimal)0.12)
                @decimal = 0;
            //If the decimal value is less than 0.37 but bigger than 0.12 set the decimal value to 0.25.
            else if (@decimal <= (decimal)0.37)
                @decimal = (decimal)0.25;
            //If the decimal value is less than 0.62 but bigger than 0.37 set the decimal value to 0.5.
            else if (@decimal <= (decimal)0.62)
                @decimal = (decimal)0.5;
            //If the decimal value is less than 0.88 but bigger than 0.62 set the decimal value to 0.75.
            else if (@decimal <= (decimal)0.88)
                @decimal = (decimal)0.75;
            //If the decimal value is bigger than 0.88 set the decimal value to 1.
            else
                @decimal = 1;

            if(@decimal == 1)
            {
                integral++;
                @decimal--;
            }

            //If the number was negative, switch it back to negative.
            if (!positive)
            {
                return (-1) * (integral + @decimal);
            }

            return integral + @decimal;
        }

        // GET: Searches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Search search = db.Searches.Find(id);
            if (search == null)
            {
                return HttpNotFound();
            }
            return View(search);
        }

        // GET: Searches/Create
        public ActionResult Create()
        {
            //Create the list of states
            List<string> states = new List<string>();
            states.Add("---");
            foreach(string state in db.States.Select(s => s.StateName).ToList())
            {
                states.Add(state);
            }
            ViewBag.States = states;

            //Create the list of stars
            List<string> stars = new List<string>();
            stars.Add("No Preference");
            stars.Add("0-1");
            stars.Add("1-2");
            stars.Add("2-3");
            stars.Add("3-4");
            stars.Add("4-5");
            ViewBag.Stars = stars;

            //Create the list of flight types
            List<string> types = new List<string>();
            types.Add("Economy");
            //Types.Add("First Class");
            ViewBag.Flight = types;

            return View();
        }

        // POST: Searches/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StartDate,EndDate,NumTravelers,MaxAmount")] SearchDashBoardVM searchVM, int? sAirport, int? eAirport, string HotelStarValue, string FlightType)
        {          
            //Get the username of the user that is logged in.
            string userName = User.Identity.Name;

            //Find the userID for the person logged in.
            string userID = userDB.Users
                .Where(u => u.UserName == userName)
                .Select(un => un.Id).FirstOrDefault();

            //Find the personID for the person logged in.
            int? personID = db.People
                .Where(p => p.UserID == userID)
                .Select(u => u.PersonID).FirstOrDefault();

            int id = -5;

            //If there is no user logged in, set the userID to -1, otherwise set it to the user logged in.
            if (personID == null || personID == 0)
            {
                id = -1;
            }
            else
            {
                id =  (int)personID;
            }

            //Find the corresponding numbers or symbols for the given inputs of the star value and flight type.
            int star = GetHotelStarValue(HotelStarValue);
            string type = GetFlightType(FlightType);
            
            if(sAirport == null | eAirport == null)
            {
                //Create the list of states
                List<string> stateList = new List<string>();
                stateList.Add("---");
                foreach (string state in db.States.Select(s => s.StateName).ToList())
                {
                    stateList.Add(state);
                }
                ViewBag.States = stateList;

                //Create the list of stars
                List<string> starList = new List<string>();
                starList.Add("No Preference");
                starList.Add("0-1");
                starList.Add("1-2");
                starList.Add("3-4");
                starList.Add("4-5");
                ViewBag.Stars = starList;

                //Create the list of flight types
                List<string> typeList = new List<string>();
                typeList.Add("Economy");
                //TypeList.Add("First Class");
                ViewBag.Flight = typeList;

                return View();
            }

            //Create the search (hopefully...)
            Search search = new Search { UserID = id, NumTravelers = searchVM.NumTravelers, StartDate = searchVM.StartDate, EndDate = searchVM.EndDate, MaxAmount = searchVM.MaxAmount, StartAirport = (int)sAirport, EndAirport = (int)eAirport, HotelStarValue = star, FlightType = type };

            if (ModelState.IsValid)
            {                               
                //Get the starting airport code from the DB
                string startAirPort = db.Airports
                    .Where(a => a.AirportID == sAirport)
                    .Select(a => a.AirportCode)
                    .FirstOrDefault();

                //Get the airport code for the ending airport
                string endAirPort = db.Airports
                    .Where(a => a.AirportID == eAirport)
                    .Select(a => a.AirportCode)
                    .FirstOrDefault();

                //Get the foodCost based on the ending state

ReadyGOTravel/readygotravel/readygotravel/Views/Searches/Delete.cshtml
@model readygotravel.Models.Search

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Search</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Person.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.UserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumTravelers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumTravelers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartAirport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartAirport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndAirport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndAirport)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ReadyGOTravel/readygotravel/readygotravel/Views/Searches/DeleteAll.cshtml
@{
    ViewBag.Title = "DeleteAll";
}

<div class="container">
    <div class="jumbotron">
        <h2>Clear Search History</h2>
        <hr />
        <h4>Search History Count: @ViewBag.searchesCount</h4>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">

                @*check if has have any searches to display and then display message depending on that.*@
                @if (ViewBag.searchesCount >= 1)
                {
                    <h4>Are you sure you want to clear your search history?</h4>


                    @*Button to confirm deletion of search history*@
                    <input type="submit" value="yes" class="btn btn-default" />

                    @*Button to return to Search History page*@
                    @Html.ActionLink("No", "UserSearches", "Searches", null, new { @class = "btn navbar-btn" })

                }
                else
                {
                    <h4>No searches in your search history? Have a budget and a destination you want to go to?</h4>
                    <h4> Try making some searches @Html.ActionLink("here.", "Create", "Search")</h4>
                    @*Button to return to Search History page*@
                    @Html.ActionLink("Back", "UserSearches", "Searches", null, new { @class = "btn navbar-btn" })
                }
            </div>
        }

    </div>
</div>

ReadyGOTravel/readygotravel/readygotravel/Views/Searches/Details.cshtml
@model readygotravel.Models.Search

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Search</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Person.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.UserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumTravelers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumTravelers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartState)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartState)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndState)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndState)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SearchID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ReadyGOTravel/readygotravel/readygotravel/Views/Searches/Index.cshtml
@model IEnumerable<readygotravel.Models.Search>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Person.UserID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumTravelers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaxAmount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartAirport)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndAirport)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Person.UserID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumTravelers)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MaxAmount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartAirport)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndAirport)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SearchID }) |
            @Html.ActionLink("Details", "Details", new { id=item.SearchID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.SearchID })
        </td>
    </tr>
}

</table>

ReadyGOTravel/readygotravel/readygotravel/Views/Searches/Result.cshtml
@model  readygotravel.Models.Result
﻿@{
    ViewBag.Title = "Can You Afford It?";
}

<div class="content">
    @{
        @**Situation where the user has the budget to go**@
        if (ViewBag.Result == 0)
        {
            <h2>Your Results are in...</h2>
            <div class="row">
                <div class="mx-auto d-block">
                    <img src="@Url.Content("~/Content/Images/CanGo.png")" style="width:210px; height:170px" />
                </div>
            </div>
            <div class="row" align="center">
                <div class="mx-auto d-block">
                    <h4>@ViewBag.Message @string.Format("{0:C}", ViewBag.Total)</h4>
                </div>
            </div>
            <div class="row">
                <div class="mx-auto d-block">
                    <h4>@ViewBag.Message2 @string.Format("{0:C}", ViewBag.Remaining)</h4>
                </div>
            </div>
        }
        @**Situation where the user is just alittle short on budget**@
        else if (ViewBag.Result == 1)
        {
            <h2>Your Results are in...</h2>
            <div class="row">
                <div class="mx-auto d-block">
                    <img src="@Url.Content("~/Content/Images/AlmostGo.png")" style="width:210px; height:170px" class="img-responsive" />
                </div>
            </div>
            <div class="row">
                <div class="mx-auto d-block">
                    <h4>@ViewBag.Message @string.Format("{0:C}", ViewBag.Remaining)</h4>
                </div>
            </div>
        }
        @**Situation where the user does not have the budget necessary**@
        else if (ViewBag.Result == 2)
        {
            <h2>Your Results are in...</h2>
            <div class="row">
                <div class="mx-auto d-block">
                    <img src="@Url.Content("~/Content/Images/CannotGo.png")" align="middle" style="width:210px; height:170px" />
                </div>
            </div>
            <div class="row">
                <div class="mx-auto d-block">
                    <h4>@ViewBag.Message @string.Format("{0:C}", ViewBag.Remaining)</h4>
                </div>
            </div>
        }
        @**Situation where the user chose the same start and ending location (flight API error)**@
        else if (ViewBag.Result == 3)
        {
            <div class="row">
                <div class="mx-auto d-block">
                    <img src="@Url.Content("~/Content/Images/UserError.png")" style="width:210px; height:170px" />
                </div>
            </div>
            <div class="row" align="center">
                <div class="mx-auto d-block">
                    <h4>@ViewBag.Message</h4>
                </div>
            </div>
            <div class="row">
                <div class="mx-auto d-block">
                    <h4>@ViewBag.Message2</h4>
                </div>
            </div>
            <input class="btn btn-default" type="button" value="Search Again" onclick="location.href='@Url.Action("Create", "Searches")'" />
        }
        @**Situation where the user requested flight information and there were no flights that matched that criteria**@
        else
        {
            <div class="row">
                <div class="mx-auto d-block">
                    <img src="@Url.Content("~/Content/Images/NoFly.png")" style="width:210px; height:170px" />
                </div>
            </div>
            <div class="row" align="center">
                <div class="mx-auto d-block">
                    <h4>@ViewBag.Message</h4>
                </div>
            </div>
            <div class="row">
                <div class="mx-auto d-block">
                    <h4>@ViewBag.Message2</h4>
                </div>
            </div>
            <input class="btn btn-default" type="button" value="Search Again" onclick="location.href='@Url.Action("Create", "Searches")'" />

        }
    }
</div>
@{
    @**If there are no errors in the flight results, then break down the budget**@
    if (ViewBag.Result != 3 && ViewBag.Result != 4)
    {
        <div class="content">
            <h2>Budget Breakdown:</h2>
            <hr />
            <div class="d-flex justify-content-end">
                <div class="row">
                    <h6>Total Budget Allocated:&nbsp;</h6><h6 class="text-success">@string.Format("{0:C}", ViewBag.Total + ViewBag.Remaining)</h6>
                </div>
            </div>
            <div class="d-flex justify-content-end">
                <div class="row">
                    <h6>Total Flight Cost to go from @Html.DisplayFor(m => m.Search.Airport.State.StateName) (@Html.DisplayFor(m => m.Search.Airport.AirportCode) Airport) to @Html.DisplayFor(m => m.Search.Airport1.State.StateName) (@Html.DisplayFor(m => m.Search.Airport1.AirportCode) Airport):&nbsp;</h6><h6 class="text-danger"> -$@Html.DisplayFor(m => m.AvgFlightAmount)</h6>
                </div>
            </div>
            <div class="d-flex justify-content-end">
                <div class="row">
                    @if (Model.AvgHotelAmount != (decimal)0.00)
                    {
                        <h6>Total Hotel Cost for @Html.DisplayFor(m => m.Search.NumTravelers) people staying for @ViewBag.NumDays days will be around:&nbsp;</h6><h6 p class="text-danger"> -$@Html.DisplayFor(m => m.AvgHotelAmount)</h6>
                    }
                </div>
            </div>
            <div class="d-flex justify-content-end">
                <div class="row">
                    <h6>Total Food Cost for @Html.DisplayFor(m => m.Search.NumTravelers) people over @ViewBag.NumDays days will be around:&nbsp;</h6><h6 class="text-danger"> -$@Html.DisplayFor(m => m.AvgFoodCost)</h6>
                </div>
            </div>
            <hr />
            @if (ViewBag.Result >= 1)
            {
                <div class="d-flex justify-content-end">
                    <div class="row">
                        <h6>This is how much additional funds you would need: &nbsp;</h6><h6 class="text-danger">=@string.Format("{0:C}", ViewBag.Remaining) </h6>
                    </div>
                </div>
            }
            else
            {
                <div class="d-flex justify-content-end">
                    <div class="row">
                        <h6>This is your remaining budget for entertainment and transportation:&nbsp;</h6><h6 class="text-success">=@string.Format("{0:C}", ViewBag.Remaining) </h6>
                    </div>
                </div>
            }
            <br />

            <div class="d-flex justify-content-end">
                <div class="row">
                    @if (Model.AvgHotelAmount != (decimal)0.00)
                    {
                        <h6>The average hotel star value that was calculated based on your input is: @Html.DisplayFor(m => m.AvgHotelStar)</h6>
                    }
                    @if (Model.AvgHotelAmount == (decimal)0.00)
                    {
                        <h6>There were no hotels found given your search parameters</h6>
                    }
                </div>
            </div>
            <div class="d-flex justify-content-end">
                <div class="row">
                    @if (Model.AvgHotelAmount != (decimal)0.00)
                    {

                        for (int i = 0; i < ViewBag.Stars; i++)
                        {
                            <img src="@Url.Content("~/Content/Images/Star.PNG")" align="middle" style="width:30px; height:20px" />

                        }
                        if (ViewBag.Decimal == (decimal)0.25)
                        {
                            <img src="@Url.Content("~/Content/Images/1-4Star.PNG")" align="middle" style="width:30px; height:20px" />
                        }
                        if (ViewBag.Decimal == (decimal)0.5)
                        {
                            <img src="@Url.Content("~/Content/Images/1-2Star.PNG")" align="middle" style="width:30px; height:20px" />
                        }
                        if (ViewBag.Decimal == (decimal)0.75)
                        {
                            <img src="@Url.Content("~/Content/Images/3-4Star.PNG")" align="middle" style="width:30px; height:20px" />
                        }
                    }
                    
                </div>
            </div>
            <input class="btn btn-default" type="button" value="Search Again" onclick="location.href='@Url.Action("Create", "Searches")'" />
        </div>
        <div class="content">
            <h2 style="font-size:large;">Disclaimer</h2>
            <div class="row">
                <p style="font-size: smaller">
                    Here at ReadyGO-Travel, our goal is to assist you with balancing your travel budget while
                    providing you with the best hotel and flight costs options available. We in no way can
                    gaurantee "exact" pricing simply due to the nature of what our site aims to
                    provide.  We focus more on averaging costs in an attempt to prepare you for the overall amount
                    total so that you can get a generalized idea and plan your budget accordingly.
                    To find out more about how this information is calculated, please click on the button below:
                </p>
            </div>
            <div class="row">
                <div class="mx-auto d-block">
                    <input id="submit" class="btn btn-default" type="submit" value="Disclaimer Details" onclick="detailsClicked()" style="visibility:visible" />
                    <p id="flight" align="left" style="font-size: smaller">
                    </p>
                </div>
            </div>
            <div class="appendLoc">
            </div>
            <br />
            <div class="mx-auto d-block">
                <h2 style="font-size:large;">Sites to Book your Flight/Hotel</h2>
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-2">
                        <h6><a href="https://www.priceline.com/?tab=vacations">Priceline</a></h6>
                    </div>
                    <div class="col-md-2">
                        <h6><a href="https://www.expedia.com/">Expedia</a></h6>
                    </div>
                    <div class="col-md-2">
                        <h6><a href="https://www.tripadvisor.com">TripAdvisor</a></h6>
                    </div>
                    <div class="col-md-3"></div>
                </div>
            </div>
        </div>
    }
}
<br />
<br />


@section PageScripts{
    <script type="text/javascript" src="~/Scripts/Disclaimer.js"></script>

}

ReadyGOTravel/readygotravel/readygotravel/Views/Searches/UserSearches.cshtml
@model IEnumerable<readygotravel.Models.Search>
@{
    ViewBag.Title = "Search History";
}

<div class="container">
    <div class="jumbotron">
        <h2>Search History</h2>
        @if (ViewBag.TotalSearches != 0)
        {
            <div class="text-right">
                <!--button to go to clear search history page-->
                @Html.ActionLink("Clear Search History", "DeleteAll", "Searches", null, new { @class = "btn navbar-btn" })
                
            </div>
        }
        <hr />
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.StartDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumTravelers)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MaxAmount)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.StartAirport)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndAirport)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.HotelStarValue)
                </th>
                @*<th></th>*@
            </tr>
        </table>

        <!--Used this to reference how many search items are on display-->
        <input type="hidden" value=0 id="TotalElements">
        <input type="hidden" value=@ViewBag.TotalSearches id="TotalSearches">

        <!--"load more" button-->
        <div class="text-center">
            @Html.TextBox("submited", "Load More", htmlAttributes: new { @class = "btn", type = "submit", style = "max-width:250px; display:none" })
        </div>
        <hr />
        @Html.ActionLink("Back to Profile", "Details", "People", null, new { @class = "btn navbar-btn" })
    </div>
</div>


@section PageScripts{
    <script type="text/javascript" src="~/Scripts/AddMoreSearches.js"></script>

}